"use strict";
let isRaining = false;
isRaining = true;
let age = 27;
let height = 1.75;
const nationality = 'Brazilian';
const people = ['lucas', 'fernando'];
const tecnology = ['html', 'css', 'js'];
const grades = [7, 8, 9, 10];
const list = ['gian', true, 27];
let anaAge = 25;
anaAge: 'twenty five years';
let apiData;
apiData: 10;
apiData: true;
apiData: [1, 2, 3];
apiData: 'string';
let course = 'front end';
